# Generated by Django 5.2.3 on 2025-07-01 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Name of category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Name of cinema')),
                ('content', models.TextField(verbose_name='Content of cinema')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Pictures')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('publish', models.BooleanField(default=True, verbose_name='Publish')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Rating of cinema')),
                ('video', models.TextField(blank=True, default='', null=True, verbose_name='Add cinema')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
